# Generated by Django 4.0.6 on 2022-07-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
